---
- hosts: local
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: download artifact from oci oss
      include_role:
        name: oci-cloud-storage
        apply:
          environment:
           OCI_CLI_AUTH: "instance_principal"        
        tasks_from: download.yml
      vars:
        local_file_or_folder_path: "{{ artifact_path }}"
        oss_bucket_name: "{{ artifacts_container }}"
        oss_object_name: "{{ artifact }}"